# ansible-playbook playbooks/timezone/timezone.yaml --verbose --user rod --private-key ~/.ssh/id_rsa  --inventory $(pwd)/hosts/dev

- name: timezone
  hosts: raspi
  become: true
  become_method: sudo

  tasks:
    - name: Set timezone
      timezone:
        name: America/Los_Angeles
    
    - name: Restart the cron service
      systemd:
        name: cron
        state: restarted
