# ansible-playbook playbooks/docker/docker.yaml --verbose --user rod --private-key ~/.ssh/id_rsa  --inventory $(pwd)/hosts/dev

# Ref:  https://docs.docker.com/engine/install/ubuntu/
# NOTE:  Had to use deb packages because no arm64 packages were available for: 
# docker-ce
# docker-ce-cli
# containerd.io
# docker-compose-plugin

- name: docker
  hosts: raspi
  become: true
  become_method: sudo

  tasks:
    - name: Remove old versions of Docker
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-engine
        - docker.io

    - name: Ensure that deb repository dependencies are installed
      apt:
        name: xz-utils
        state: present
        
    - name: Install Docker Engine
      apt:
        deb: "{{ item }}"
        state: present
      loop:
        - https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/arm64/containerd.io_1.6.6-1_arm64.deb 
        - https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/arm64/docker-ce-cli_20.10.17~3-0~ubuntu-jammy_arm64.deb    
        - https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/arm64/docker-ce_20.10.17~3-0~ubuntu-jammy_arm64.deb 
        - https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/arm64/docker-compose-plugin_2.6.0~ubuntu-jammy_arm64.deb  
